### ISSUE TITLE
Promote ILP workshop on front page

### ISSUE THREAD

**Issue by justmoon** [interledger/interledger.github.io#13]
Let's add a banner on the front page to advertise the workshop in July.

**Comment by bsteinlo** [comment]
@justmoon Can this wait until Tuesday? Would like to work with Fabian on design, otherwise I can make it work.

**Comment by justmoon** [comment]
Tuesday is fine! Thanks in advance!

**Comment by bsteinlo** [comment]
Added banner to homepage
