### ISSUE TITLE
Remove deprecated specs from `dactyl-config.yml`

### ISSUE THREAD

**Issue by sappenin** [interledger/interledger.github.io#133]
Certain RFCs are still contained in the `dactyl-config.yml` (see [here](https://github.com/interledger/interledger.github.io/pull/132/files#diff-df88fe3fe65790837d352b0e9eee06ebR296)). If an RFC is no longer defined in the main [rfcs](https://github.com/interledger/rfcs) repo (for example, it has been moved to the [deprecated](https://github.com/interledger/rfcs/tree/master/deprecated) folder) then we should remove it from the dactyl config.

To determine this, we probably need to perform an audit of all RFC specs defined in the [dactyl config file](https://github.com/interledger/interledger.github.io/blob/master/_dactyl/dactyl-config.yml). Additionally, we should compare this against what's _actually_ on [interledger.org in the side-bar](https://interledger.org/overview.html).

I can't assign this to @LoisRP, but this relates to #132.

@mDuo13 @ryangyoung

**Comment by LoisRP** [comment]
I believe this has been resolved now with the latest merge.
