### ISSUE TITLE
Fix broken `Back to Overview` links on docs pages

### ISSUE THREAD

**Issue by emschwartz** [interledger/interledger.github.io#14]
On https://interledger.org/five-bells-ledger/apidoc/ the back to overview link doesn't work

**Comment by bsteinlo** [comment]
Fixed with this commit: https://github.com/interledger/apidoc-template/commit/272a46ff87d00cd9b252cc13f1159a8f8c96978d just need to regenerate the docs

**Comment by bsteinlo** [comment]
It appears that main.js wasn't copied over from the new repo, see https://interledger.org/five-bells-notary/apidoc/main.js
