### ISSUE TITLE
"Interledger team" link issues

### ISSUE THREAD

**Issue by marsface** [interledger/interledger.github.io#18]
In the footer, "interledger team" has no link.

in https://interledger.org/rfcs/0001-interledger-architecture/#application-layer-2, the "interledger team" is mixed with the side menu text. This is caused by the footer having no restrictions to invade the content's area. It happens in other pages if you scroll down.

**Comment by bsteinlo** [comment]
No link is intentional, for now. Looking into the other issues.

**Comment by bsteinlo** [comment]
Fixed: https://github.com/interledger/interledger.github.io/pull/22
