### ISSUE TITLE
Anchors not working on five-bells-condition readme

### ISSUE THREAD

**Issue by mDuo13** [interledger/interledger.github.io#29]
https://interledger.org/five-bells-condition/jsdoc/

The table of contents has various links to later in the document, which it assumes will work like on GitHub. They don't.

Compare with the original, where (most of) the links work:
https://github.com/interledger/five-bells-condition#table-of-contents

The page on interledger.org doesn't have IDs for the headers. That's probably the fault of whatever parser is generating the HTML from Markdown. (Some parsers have an option to generate IDs. Some parsers just... don't generate IDs.)

**Comment by adrianhopebailie** [comment]
This page is now at: https://interledgerjs.github.io/five-bells-condition/jsdoc/
