### ISSUE TITLE
Add jobs page to let community advertise ILP related jobs

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/interledger.github.io#42]
A number of participants have expressed a desire to build teams with ILP experience and work on ILP related projects. We can add a page to the website (updated via PR) that allows any community member to post job listings that include work on ILP.

Q: Should it be mandatory that any jobs listed included contributing back to the project as a deliverable?

**Comment by emschwartz** [comment]
I think requiring at least 10-20% of the position to be contributing to the open source project would be a fair requirement

**Comment by diminator** [comment]
In favor for adding more devs to the community
I would say, yes - but as long as the company branding in the listings is subtle to almost anonymous

> Q: Should it be mandatory that any jobs listed included contributing back to the project as a deliverable?

Having some commitment emerge from successful hires to the project - however difficult to measure
In the ideal case, contributions get tips and bounties through `ilp.github.com` :)

**Comment by adrianhopebailie** [comment]
> In the ideal case, contributions get tips and bounties through ilp.github.com :)

👍

**Comment by Chococoin** [comment]
Don't you need a Spanish translator to bring more people to the proyect? I may translate content into Spanish.

Regards.

**Comment by sappenin** [comment]
Closing this as stale - the ILP forum probably serves this purpose well now.
