### ISSUE TITLE
Add Github Logo next to link

### ISSUE THREAD

**Issue by emschwartz** [interledger/interledger.github.io#57]
Multiple people have come to the website and said they didn't realize it was open source. We should add the Github logo next to the link text to draw a little more attention to that.

**Comment by bsteinlo** [comment]
@emschwartz adding a Github logo next to the link is totally fine, however what do you think about also adding 'open source' in the hero byline so it reads 'The open source protocol for connecting....'. Let me know your thoughts and I can do it in 1 PR.

**Comment by adrianhopebailie** [comment]
I also think people are familiar with seeing the phrase "Fork this on Github" or similar somewhere. Is there some place it makes sense to include that?

**Comment by emschwartz** [comment]
"Open source protocol" sounds a little odd to me because I think of "open source" as referring to source code whereas protocols might be "open" or "standard", etc.

I think the "Fork me on Github" may have fallen a bit out of fashion (I was having trouble finding it on sites when I was looking for examples) but I'd be open to the option if I'm wrong about that.

**Comment by bsteinlo** [comment]
Agreed that "Fork me on Github"  is outdated. Moreover, it doesn't describe the user action, in that clicking the link does not link to a single repo which a user would fork, but rather a library of repos, so I am adverse to using a label which doesn't describe the action.

**Comment by emschwartz** [comment]
I think just having the Github logo would help call attention to that a little more so I think that would be fine, at least for now.

**Comment by adrianhopebailie** [comment]
Fixed in b6ad7ee
