### ISSUE TITLE
Remove ilp-kit api documentation?

### ISSUE THREAD

**Issue by michielbdejong** [interledger/interledger.github.io#62]
For quotes and payments, we want people to either write their own test scripts and client software using the ilp module, or use Dennis's new CLI tools, or directly speak CLP on the wire.

We no longer want people to write software that talks to the ilp-kit api. So should we just remove the link to https://interledgerjs.github.io/ilp-kit/apidoc/? There's currently a link from https://interledger.org/overview.html (left Technical Documentation -> ilp-kit).

**Comment by dappelt** [comment]
Yes, I think we should remove the link. We probably want to replace most of the links under _Technical Documentation_, like fb-ledger, ilp-connector etc.

**Comment by michielbdejong** [comment]
@adrianhopebailie what do you think?

**Comment by adrianhopebailie** [comment]
@michielbdejong : I gave a 👍 above

**Comment by michielbdejong** [comment]
Done, see https://github.com/interledger/interledger.github.io/search?utf8=✓&q=ilp-kit
