### ISSUE TITLE
Review code samples on home page

### ISSUE THREAD

**Issue by michielbdejong** [interledger/interledger.github.io#66]
The code samples on the home page use `import` so they won't work in nodejs. I also can't see how they would work in the browser. When you click 'Try it out', you get pointed to ilp-kit, and we know from the questions people ask in gitter, that the ilp-kit API is what most developers focus on.

As we start merging the [tutorials](https://github.com/interledger/tutorials/pulls), we should probably remove the code samples from the interledger.org homepage, and point to the Letter Shop tutorial instead?

**Comment by michielbdejong** [comment]
@adrianhopebailie what do you think? Shall I prepare a PR for that?

**Comment by bsteinlo** [comment]
@michielbdejong could I request that you post a preview of this on a forked gh-pages so I can visually check it out? We made the visual on the right correspond to the height and everything of the code samples, so I just want to make sure it doesn't break. Thanks!

**Comment by michielbdejong** [comment]
Maybe we can keep the teaser snippets on there, but when people click 'Try it out' we then send them to https://interledger.org/tutorials/letter-shop?

**Comment by emschwartz** [comment]
I agree we should update the snippets sometime in the near future. Maybe we should wait until we figure out the `ilp-plugin` thing and possibly @justmoon's ILP Quickstart thing. Once the tutorials are ready to go I think it would be a good idea to link them from there

**Comment by bsteinlo** [comment]
I like the idea of keeping the snippets (which maintains the design) and
then sending them to the tutorial when clicking "Try it out". Then we can
update the snippets when ready.

Ben Stein-Lobovits
Lead Web & Analytics Engineer | Ripple
ben@ripple.com | ripple.com

**Comment by adrianhopebailie** [comment]
+1

**Comment by michielbdejong** [comment]
Done, see https://interledger.org/
